# Generated by Django 4.1.7 on 2023-04-17 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppealsCourt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('address', models.TextField(max_length=200)),
                ('account', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('address', models.TextField(max_length=200)),
                ('account', models.TextField(blank=True, max_length=500)),
                ('compensation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('region_id', models.CharField(max_length=2)),
                ('region_name', models.TextField(max_length=100)),
                ('relevant_on', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=30)),
                ('ogrn', models.CharField(max_length=13, unique=True)),
                ('inn', models.CharField(max_length=11, unique=True)),
                ('address', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plaintiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=30)),
                ('ogrn', models.CharField(max_length=13, unique=True)),
                ('inn', models.CharField(max_length=11, unique=True)),
                ('address', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('card', models.URLField(blank=True, unique=True)),
                ('overall_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gp_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appeals_court', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.appealscourt')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.court')),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.defendant')),
                ('plaintiff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plaintiff')),
            ],
            options={
                'unique_together': {('court', 'id')},
            },
        ),
    ]
