# Generated by Django 4.1.7 on 2023-05-21 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppealsCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название суда')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
                ('account', models.TextField(blank=True, max_length=500, verbose_name='Банковские реквизиты')),
                ('relevant_on', models.CharField(blank=True, max_length=50, verbose_name='Актуально на')),
                ('reg_id', models.CharField(max_length=2, verbose_name='Код региона')),
                ('reg_name', models.TextField(max_length=100, verbose_name='Название региона')),
                ('compensation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Апелляционный суд',
                'verbose_name_plural': 'Апелляционные суды',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название суда')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
                ('account', models.TextField(blank=True, max_length=500, verbose_name='Банковские реквизиты')),
                ('relevant_on', models.CharField(blank=True, max_length=50, verbose_name='Актуально на')),
                ('reg_id', models.CharField(max_length=2, verbose_name='Код региона')),
                ('reg_name', models.TextField(max_length=100, verbose_name='Название региона')),
                ('compensation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Суд первой инстанции',
                'verbose_name_plural': 'Суды первой инстанции',
            },
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=30, verbose_name='Короткое наименование')),
                ('ogrn', models.CharField(max_length=13, unique=True, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=10, unique=True, verbose_name='ИНН')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Ответчик',
                'verbose_name_plural': 'Ответчики',
            },
        ),
        migrations.CreateModel(
            name='Plaintiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=30, verbose_name='Короткое наименование')),
                ('ogrn', models.CharField(max_length=13, unique=True, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=10, unique=True, verbose_name='ИНН')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Истец',
                'verbose_name_plural': 'Истцы',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('card', models.URLField(blank=True, null=True, unique=True)),
                ('claim_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gp_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'В работе'), ('completed', 'Завершено'), ('no_status', 'Нет статуса')], default='no_status', max_length=20)),
                ('appeals_court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appealscourt')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.court')),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.defendant')),
                ('plaintiff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plaintiff')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('court', 'case_id'), name='unique_court_case'),
        ),
    ]
