# Generated by Django 4.1.7 on 2023-05-29 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CassationCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название суда')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
                ('account', models.TextField(blank=True, max_length=500, verbose_name='Банковские реквизиты')),
                ('relevant_on', models.CharField(blank=True, max_length=50, verbose_name='Актуально на')),
                ('reg_id', models.CharField(max_length=2, verbose_name='Код региона')),
                ('reg_name', models.TextField(max_length=100, verbose_name='Название региона')),
                ('compensation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Кассационный суд',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='court_level',
            field=models.CharField(choices=[('first', 'Первая инстанция'), ('second', 'Апелляция'), ('third', 'Кассация')], default='no_court', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.court'),
        ),
        migrations.AddField(
            model_name='case',
            name='cassation_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cassationcourt'),
        ),
    ]
