# Generated by Django 4.1.7 on 2023-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appealscourt',
            options={'verbose_name': 'Апелляционный суд', 'verbose_name_plural': 'Апелляционные суды'},
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'verbose_name': 'Суд первой инстанции', 'verbose_name_plural': 'Суды первой инстанции'},
        ),
        migrations.AlterModelOptions(
            name='defendant',
            options={'verbose_name': 'Ответчик', 'verbose_name_plural': 'Ответчики'},
        ),
        migrations.AlterModelOptions(
            name='plaintiff',
            options={'verbose_name': 'Истец', 'verbose_name_plural': 'Истцы'},
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appealscourt',
            name='account',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Банковские реквизиты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appealscourt',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='appealscourt',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название суда'),
        ),
        migrations.AlterField(
            model_name='appealscourt',
            name='reg_id',
            field=models.CharField(max_length=2, verbose_name='Код региона'),
        ),
        migrations.AlterField(
            model_name='appealscourt',
            name='reg_name',
            field=models.TextField(max_length=100, verbose_name='Название региона'),
        ),
        migrations.AlterField(
            model_name='appealscourt',
            name='relevant_on',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Актуально на'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appealscourt',
            name='zip_code',
            field=models.CharField(max_length=6, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='case',
            name='card',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='account',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Банковские реквизиты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название суда'),
        ),
        migrations.AlterField(
            model_name='court',
            name='reg_id',
            field=models.CharField(max_length=2, verbose_name='Код региона'),
        ),
        migrations.AlterField(
            model_name='court',
            name='reg_name',
            field=models.TextField(max_length=100, verbose_name='Название региона'),
        ),
        migrations.AlterField(
            model_name='court',
            name='relevant_on',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Актуально на'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='court',
            name='zip_code',
            field=models.CharField(max_length=6, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='inn',
            field=models.CharField(max_length=10, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='ogrn',
            field=models.CharField(max_length=13, unique=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='short_name',
            field=models.CharField(max_length=30, verbose_name='Короткое наименование'),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='inn',
            field=models.CharField(max_length=10, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='ogrn',
            field=models.CharField(max_length=13, unique=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='short_name',
            field=models.CharField(max_length=30, verbose_name='Короткое наименование'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('court', 'case_id'), name='unique_court_case'),
        ),
    ]
