# Generated by Django 4.1.7 on 2023-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='claim_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('active', 'В работе'), ('completed', 'Завершено'), ('no_status', 'Нет статуса')], default='no_status', max_length=20),
        ),
    ]
