# Generated by Django 4.1.7 on 2023-04-10 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_number', models.CharField(max_length=30)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.court')),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.defendant')),
                ('plaintiff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plaintiff')),
            ],
        ),
    ]
