# Generated by Django 4.1.7 on 2023-05-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_case_claim_price_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='overall_charge',
        ),
    ]
