# Generated by Django 4.1.7 on 2023-04-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appealscourt_options_alter_court_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
        migrations.AlterField(
            model_name='case',
            name='appeals_court',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.appealscourt'),
        ),
    ]
