# Generated by Django 4.1.7 on 2023-04-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='court_number',
            new_name='case_number',
        ),
    ]
