# Generated by Django 4.1.7 on 2023-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_court_number_case_case_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='case',
            name='card',
            field=models.URLField(blank=True),
        ),
    ]
