# Generated by Django 4.1.7 on 2023-04-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_case_options_alter_case_appeals_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='appeals_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appealscourt'),
        ),
    ]
