# Generated by Django 4.1.7 on 2023-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_case_gp_charge_case_overall_charge_court_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='card',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='inn',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='ogrn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='inn',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='plaintiff',
            name='ogrn',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
